version: '2'
services:
  example:
    image: openjdk:11-slim
    working_dir: /src
    command: ./gradlew run --continuous
    volumes:
      - '.:/src'
      - '/src/build/'
      - '/src/.gradle'
      - 'gradle-cache:/root/.gradle/caches/modules-2/files-2.1/'
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: always
    privileged: true
    stdin_open: true
    tty: true
  example-db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  pg-admin:
    image: thajeztah/pgadmin4
    restart: always
    ports:
      - "5151:5050"
volumes:
  gradle-cache:
